name: dye-the-world

services:
  server:
    container_name: server
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: 3G
      TYPE: FORGE
      VERSION: 1.20.1
      FORGE_VERSION: 47.3.10
      PACKWIZ_URL: http://host.docker.internal:8080/pack.toml
      RCON_CMDS_STARTUP: dump registry minecraft:item
    volumes:
      - ./data:/data
      - ./dump:/data/dump
