name = "Arva"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c44fec9eb89fba45e95c5c193b057fe968318092f987a3faf82de8fbbd61fc8f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
