name = "Arva"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4fa1a361ef5f9728109cbeacf9ba78626db94f981ab0ffefa78da96d0fd2d81"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
