name: Release Polytone
on:
  workflow_dispatch:
  push:
    branches:
      - 1.20.x
    paths:
      - polytone/*.zip

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Primes
        id: cache
        uses: actions/cache@v4
        with:
          key: polytone-${{ hashFiles('polytone/*.zip') }}

      - uses: Kir-Antipov/mc-publish@v3.3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          modrinth-id: 2j2IcOdG
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            polytone/*.zip
          version: 1.0.${{ env.GITHUB_RUN_NUMBER }}
          game-versions: |
            1.20.1
          dependencies: |
            polytone